name: Colourful
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-24.04
    steps:
      - run: |
          sudo apt-get install -y gettext bash
          curl -L -O https://launchpad.net/ubuntu/+archive/primary/+files/gettext_0.22.5-2_amd64.deb
          sudo dpkg -i gettext_0.22.5-2_amd64.deb
      - run: |
          bash -c 'for x in {0..8}; do for i in {30..37}; do for a in {40..47}; do echo -ne "\e[$x;$i;$a""m\\\e[$x;$i;$a""m\e[0;37;40m "; done; echo; done; done; echo ""'
          msgcat --version
          TERM=xterm msgcat --color=test
          TERM=xterm-256color msgcat --color=test
      - run: |
          echo -e "\x1b(BUS ASCII: Hello #"
          echo -e "\x1b(AUK ASCII: Hello #"
          echo -e "\x1b(BDEC Special Graphics: \x1b(0lqqqk"
          echo -e "\x1b(XBANG ~~~~"
          echo -e "\x1b(BInvoke G2: \x1bN#"
          echo -e "\x1b(BDesignate G2 UK ASCII and invoke G2: \x1b*A\x1bN#"
          echo -e "\x1b(BDesignate DEC Special Graphics to G3 (\x1b+0) and invoke: \x1bOq"
