name: Colourful
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-24.04
    steps:
      - run: sudo apt-get install -y gettext bash gettext
      - run: |
          bash -c 'for x in {0..8}; do for i in {30..37}; do for a in {40..47}; do echo -ne "\e[$x;$i;$a""m\\\e[$x;$i;$a""m\e[0;37;40m "; done; echo; done; done; echo ""'
          msgcat --version
          TERM=xterm msgcat --color=test
          TERM=xterm-256color msgcat --color=test
